services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-assignment
    ports:
      - "${PORT}:3000"
    environment:
      - PORT=${PORT}
      - EVM_RPC=${EVM_RPC}
      - COSMOS_RPC=${COSMOS_RPC}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

